
import React, { useState } from 'react';
import { Navigate } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { FileText, Bot, User, RefreshCw, Upload, Copy, Check } from 'lucide-react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import TextEditor from '@/components/TextEditor';

const Dashboard: React.FC = () => {
  const { currentUser } = useAuth();
  const { toast } = useToast();
  const [inputText, setInputText] = useState('');
  const [resultText, setResultText] = useState('');
  const [isDetecting, setIsDetecting] = useState(false);
  const [isHumanizing, setIsHumanizing] = useState(false);
  const [textCopied, setTextCopied] = useState(false);
  
  // Redirect if not logged in
  if (!currentUser) {
    return <Navigate to="/login" />;
  }

  const handleTextChange = (value: string) => {
    setInputText(value);
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Only accept text files
    if (!file.type.includes('text')) {
      toast({
        variant: "destructive",
        title: "Invalid file type",
        description: "Please upload a text file (.txt)"
      });
      return;
    }

    const reader = new FileReader();
    reader.onload = (event) => {
      if (event.target?.result) {
        setInputText(event.target.result as string);
      }
    };
    reader.readAsText(file);
  };

  const detectAIText = () => {
    if (!inputText.trim()) {
      toast({
        variant: "destructive",
        title: "No text provided",
        description: "Please enter or upload some text first"
      });
      return;
    }

    setIsDetecting(true);
    
    // Simulate AI detection with timeout
    setTimeout(() => {
      // In a real implementation, this would call an API
      const score = Math.random() * 100;
      const result = `
AI Detection Results:
-----------------------
AI Probability: ${score.toFixed(1)}%
Confidence: ${score > 70 ? 'High' : score > 40 ? 'Medium' : 'Low'}

Analysis:
${score > 70 
  ? 'This text was likely generated by AI. It shows patterns typical of machine-generated content.'
  : score > 40 
  ? 'This text shows some AI characteristics but also has human elements. It might be AI-generated content that was edited by a human, or sophisticated AI writing.'
  : 'This text appears to be primarily human-written. Few or no indicators of AI generation were detected.'}
`;
      
      setResultText(result);
      setIsDetecting(false);
      
      toast({
        title: "Detection complete",
        description: "AI detection analysis has been completed"
      });
    }, 2000);
  };

  const humanizeText = () => {
    if (!inputText.trim()) {
      toast({
        variant: "destructive",
        title: "No text provided",
        description: "Please enter or upload some text first"
      });
      return;
    }

    setIsHumanizing(true);
    
    // Simulate text humanization with timeout
    setTimeout(() => {
      // In a real implementation, this would call an API
      const result = `${inputText}\n\n[This text has been processed to appear more human-like. It now includes more natural language patterns, varied sentence structures, and human-like nuances.]`;
      
      setResultText(result);
      setIsHumanizing(false);
      
      toast({
        title: "Humanization complete",
        description: "Your text has been humanized successfully"
      });
    }, 2000);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(resultText);
    setTextCopied(true);
    
    toast({
      title: "Copied to clipboard",
      description: "The text has been copied to your clipboard"
    });
    
    setTimeout(() => setTextCopied(false), 2000);
  };

  return (
    <>
      <Header />
      <main className="container mx-auto px-4 py-10">
        <div className="max-w-5xl mx-auto">
          <h1 className="text-3xl font-bold mb-6">Text Analysis Dashboard</h1>
          
          <Card className="mb-8">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="w-5 h-5" />
                Text Input
              </CardTitle>
              <CardDescription>
                Paste your text below or upload a text file
              </CardDescription>
            </CardHeader>
            <CardContent>
              <TextEditor 
                value={inputText} 
                onChange={handleTextChange} 
                placeholder="Paste or type your text here..." 
              />
              
              <div className="mt-4">
                <Label htmlFor="file-upload" className="cursor-pointer">
                  <div className="flex items-center gap-2 text-sm text-primary hover:underline">
                    <Upload className="w-4 h-4" />
                    Upload text file
                  </div>
                  <input
                    id="file-upload"
                    type="file"
                    accept=".txt"
                    className="hidden"
                    onChange={handleFileUpload}
                  />
                </Label>
              </div>
            </CardContent>
            <CardFooter className="flex gap-4">
              <Button 
                onClick={detectAIText} 
                disabled={isDetecting || isHumanizing || !inputText.trim()}
                className="flex items-center gap-2"
              >
                {isDetecting ? (
                  <RefreshCw className="w-4 h-4 animate-spin" />
                ) : (
                  <Bot className="w-4 h-4" />
                )}
                {isDetecting ? "Detecting..." : "Detect AI Text"}
              </Button>
              <Button 
                onClick={humanizeText} 
                disabled={isDetecting || isHumanizing || !inputText.trim()}
                className="flex items-center gap-2"
                variant="outline"
              >
                {isHumanizing ? (
                  <RefreshCw className="w-4 h-4 animate-spin" />
                ) : (
                  <User className="w-4 h-4" />
                )}
                {isHumanizing ? "Humanizing..." : "Humanize Text"}
              </Button>
            </CardFooter>
          </Card>
          
          {resultText && (
            <Card className="animate-in slide-in-from-bottom-4 duration-300">
              <CardHeader>
                <CardTitle>Results</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="bg-muted p-4 rounded-md whitespace-pre-wrap">
                  {resultText}
                </div>
              </CardContent>
              <CardFooter>
                <Button 
                  variant="outline" 
                  size="sm" 
                  onClick={copyToClipboard}
                  className="flex items-center gap-2"
                >
                  {textCopied ? (
                    <>
                      <Check className="w-4 h-4" />
                      Copied!
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4" />
                      Copy to clipboard
                    </>
                  )}
                </Button>
              </CardFooter>
            </Card>
          )}
        </div>
      </main>
      <Footer />
    </>
  );
};

export default Dashboard;
