
const DetectionResult = require('../models/DetectionResult');

/**
 * Service for AI text detection
 * In a production environment, this would integrate with a real AI detection API
 * like GPTZero, OpenAI, or other specialized services
 */

/**
 * Detects if text is AI-generated
 * @param {string} text - The text to analyze
 * @param {string} userId - The user ID
 * @returns {Promise<Object>} Detection results
 */
async function detectAIText(text, userId = 'anonymous') {
  // This is a placeholder implementation
  // In production, you would replace this with an actual API call
  
  try {
    // Simulate API call delay
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    // Calculate text length for some basic metrics
    const textLength = text.length;
    
    // Generate a pseudo-random result based on text characteristics
    // (This is just for demonstration, not actual AI detection)
    const randomFactor = Math.random();
    const lengthFactor = Math.min(textLength / 1000, 1); // Normalize by length
    
    // Calculate a pseudo-probability (completely arbitrary for demo purposes)
    const aiProbability = (randomFactor * 0.7 + lengthFactor * 0.3) * 100;
    
    // Determine confidence level
    let confidenceLevel;
    if (aiProbability > 75) {
      confidenceLevel = 'High';
    } else if (aiProbability > 40) {
      confidenceLevel = 'Medium';
    } else {
      confidenceLevel = 'Low';
    }
    
    // Generate analysis based on the probability
    let analysis;
    if (aiProbability > 70) {
      analysis = 'This text was likely generated by AI. It shows patterns typical of machine-generated content.';
    } else if (aiProbability > 40) {
      analysis = 'This text shows some AI characteristics but also has human elements. It might be AI-generated content that was edited by a human, or sophisticated AI writing.';
    } else {
      analysis = 'This text appears to be primarily human-written. Few or no indicators of AI generation were detected.';
    }
    
    // Create detection results object
    const detectionResults = {
      aiProbability: Math.round(aiProbability * 10) / 10, // Round to 1 decimal place
      confidenceLevel,
      analysis,
      textLength
    };
    
    // Save results to MongoDB
    const detectionResult = new DetectionResult({
      userId,
      originalText: text,
      detectionResults,
      timestamp: new Date()
    });
    
    await detectionResult.save();
    
    // Return detection results
    return {
      ...detectionResults,
      timestamp: detectionResult.timestamp.toISOString(),
      resultId: detectionResult._id
    };
    
  } catch (error) {
    console.error('Error in AI detection service:', error);
    throw new Error('Failed to process AI detection');
  }
}

module.exports = {
  detectAIText
};
