// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jusuwufpgirouvyrmaxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1c3V3dWZwZ2lyb3V2eXJtYXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTc0NTYsImV4cCI6MjA2OTg5MzQ1Nn0.i97DbVHeHOjLn9noOcL-IhXZRZe62gJXGA7lYCPIWXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});